#!/usr/bin/env bash

if [ "$1" == "" ]; then
	export COFFEA_IMAGE_PATH=/cvmfs/unpacked.cern.ch/registry.hub.docker.com/$(cat ${LOCAL_DIR}/coffea-image.txt)
	# export COFFEA_IMAGE=coffeateam/coffea-dask-almalinux8:2025.1.0-py3.12
else
	export COFFEA_IMAGE=$1
fi

echo "Coffea Image: ${COFFEA_IMAGE_PATH}"

EXTERNAL_BIND=${PWD} singularity exec -B /etc/condor -B /eos -B /afs -B /cvmfs --pwd ${PWD} \
	${COFFEA_IMAGE_PATH} \
	/bin/bash --rcfile ${LOCAL_DIR}/shell-bashrc.sh
