#!/usr/bin/bash
condor_submit submit_0.sh
sleep 5
condor_submit submit_1.sh
sleep 5
condor_submit submit_2.sh
sleep 5
condor_submit submit_3.sh
sleep 5
condor_submit submit_4.sh
sleep 5
condor_submit submit_5.sh
sleep 5
condor_submit submit_6.sh
sleep 5
condor_submit submit_7.sh
sleep 5
condor_submit submit_8.sh
sleep 5
condor_submit submit_9.sh
sleep 5
condor_submit submit_10.sh
sleep 5
condor_submit submit_11.sh
sleep 5
condor_submit submit_12.sh
sleep 5
condor_submit submit_13.sh
sleep 5
condor_submit submit_14.sh
sleep 5
condor_submit submit_15.sh
sleep 5
